-keep class org.jivesoftware.smack.initializer.VmArgInitializer { *; }
-keep class org.jivesoftware.smack.** { *; }
-keep class org.jivesoftware.smackx.** { *; }
-keep class org.bouncycastle.jcajce.provider.** { *; }
-keep class net.sqlcipher.** { *; }
-keep class net.sqlcipher.database.** { *; }